### ISSUE TITLE
正常生成了项目，运行exe后vmprotectSDK64.dll报错

### ISSUE THREAD

**Issue by JuZi233** [AMXZzzz/SF_TRT_62#10]
![image](https://github.com/AMXZzzz/SF_TRT_62/assets/28708044/8dd5337a-4d34-463d-bff7-47ab82ec8c1e)

**Comment by JuZi233** [comment]
使用了项目中提供的VMProtect64.dll后则为0xc000007b应用程序无法正常启动,猜测是哪个dll的版本对不上：
名称	PID	模块名	版本	完整路径
actuator.exe	14488	ADVAPI32.dll	10.0.19041.3930	C:\Windows\System32\ADVAPI32.dll
actuator.exe	14488	bcrypt.dll	10.0.19041.3636	C:\Windows\System32\bcrypt.dll
actuator.exe	14488	combase.dll	10.0.19041.3636	C:\Windows\System32\combase.dll
actuator.exe	14488	COMDLG32.dll	10.0.19041.3758	C:\Windows\System32\COMDLG32.dll
actuator.exe	14488	CRYPTBASE.DLL	10.0.19041.3636	C:\Windows\SYSTEM32\CRYPTBASE.DLL
actuator.exe	14488	d3d11.dll	10.0.19041.3636	C:\Windows\SYSTEM32\d3d11.dll
actuator.exe	14488	dxgi.dll	10.0.19041.3636	C:\Windows\SYSTEM32\dxgi.dll
actuator.exe	14488	GDI32.dll	10.0.19041.3996	C:\Windows\System32\GDI32.dll
actuator.exe	14488	gdi32full.dll	10.0.19041.3996	C:\Windows\System32\gdi32full.dll
actuator.exe	14488	KERNEL32.DLL	10.0.19041.3636	C:\Windows\System32\KERNEL32.DLL
actuator.exe	14488	KERNELBASE.dll	10.0.19041.3996	C:\Windows\System32\KERNELBASE.dll
actuator.exe	14488	msvcp_win.dll	10.0.19041.3636	C:\Windows\System32\msvcp_win.dll
actuator.exe	14488	msvcrt.dll	7.0.19041.3636	C:\Windows\System32\msvcrt.dll
actuator.exe	14488	ntdll.dll	10.0.19041.3996	C:\Windows\SYSTEM32\ntdll.dll
actuator.exe	14488	ole32.dll	10.0.19041.3636	C:\Windows\System32\ole32.dll
actuator.exe	14488	OLEAUT32.dll	10.0.19041.3636	C:\Windows\System32\OLEAUT32.dll
actuator.exe	14488	onnxruntime.dll	1.0.1911.2111	C:\Windows\SYSTEM32\onnxruntime.dll
actuator.exe	14488	RPCRT4.dll	10.0.19041.3758	C:\Windows\System32\RPCRT4.dll
actuator.exe	14488	sechost.dll	10.0.19041.3930	C:\Windows\System32\sechost.dll
actuator.exe	14488	shcore.dll	10.0.19041.3636	C:\Windows\System32\shcore.dll
actuator.exe	14488	SHELL32.dll	10.0.19041.3996	C:\Windows\System32\SHELL32.dll
actuator.exe	14488	ucrtbase.dll	10.0.19041.3636	C:\Windows\System32\ucrtbase.dll
actuator.exe	14488	USER32.dll	10.0.19041.3996	C:\Windows\System32\USER32.dll
actuator.exe	14488	VMProtectSDK64.dll		C:\Windows\SYSTEM32\VMProtectSDK64.dll
actuator.exe	14488	win32u.dll	10.0.19041.3996	C:\Windows\System32\win32u.dll
actuator.exe	14488	WS2_32.dll	10.0.19041.3636	C:\Windows\System32\WS2_32.dll
actuator.exe	14488	cudart64_12.dll	6.14.11.12030	D:\NVIDIA\CUDAVER12\bin\cudart64_12.dll
actuator.exe	14488	nvinfer.dll		D:\NVIDIA\TensorRT-8.6.1.6\lib\nvinfer.dll
actuator.exe	14488	opencv_world480.dll	4.8.0.0	D:\opencv\opencv\build\x64\vc16\bin\opencv_world480.dll
actuator.exe	14488	actuator.exe		E:\pubgtool\SF_TRT_62\build\Release\actuator.exe

**Comment by AMXZzzz** [comment]
bin文件夹下应该有对应的dll

**Comment by AMXZzzz** [comment]
我认为这个问题已经解决，如果还有问题，请开始新的话题。

**Comment by JuZi233** [comment]
首先，我的bin文件下、肯定是有对应的dll文件，至于版本，我的windows自带没有这个dll，往上搜索到的64，32对应的版本我都试过，统一报这个错，不过你关了吧。

**Comment by AMXZzzz** [comment]
> 首先，我的bin文件下、肯定是有对应的dll文件，至于版本，我的windows自带没有这个dll，往上搜索到的64，32对应的版本我都试过，统一报这个错，不过你关了吧。

依赖dll需要和exe放在同一目录下
