### ISSUE TITLE
AMD GPU

### ISSUE THREAD

**Issue by Seemslegitx** [AMXZzzz/SF_TRT_62#11]
Hello, I've been struggling to compile the project for the past two days because I'm using an AMD GPU. How can I compile the project only for DirectML?

**Comment by AMXZzzz** [comment]
I will upload a DML project when I have time

**Comment by Seemslegitx** [comment]
> I will upload a DML project when I have time

👀

**Comment by AMXZzzz** [comment]
need to wait for my laptop purchase, it won’t be long

**Comment by AMXZzzz** [comment]
> 您好，由于我使用的是 AMD GPU，因此过去两天我一直在努力编译项目。我该如何仅为 DirectML 编译项目？

https://github.com/AMXZzzz/SF_DML.git

Sorry, it's been so long.
