### ISSUE TITLE
cmake不了

### ISSUE THREAD

**Issue by loadingfd** [AMXZzzz/SF_TRT_62#4]
`The C compiler identification is MSVC 19.36.32535.0
The CXX compiler identification is MSVC 19.36.32535.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Found Threads: TRUE  
The CUDA compiler identification is NVIDIA 11.6.55
Detecting CUDA compiler ABI info
Detecting CUDA compiler ABI info - failed
Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/nvcc.exe
Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/nvcc.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCUDACompiler.cmake:100 (message):
  The CUDA compiler

    "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/nvcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: 'E:/Download/Compressed/SF_TRT_62-master_2/SF_TRT_62-master/build/CMakeFiles/CMakeScratch/TryCompile-gepjo4'
    
    Run Build Command(s): "E:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_b1812.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
    MSBuild version 17.6.3+07e294721 for .NET Framework

    生成启动时间为 2023/10/17 22:24:16。

    

    节点 1 上的项目“E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj”(默认目标)。

    PrepareForBuild:

      正在创建目录“cmTC_b1812.dir\Debug\”。

      正在创建目录“E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\Debug\”。

      正在创建目录“cmTC_b1812.dir\Debug\cmTC_b1812.tlog\”。

    InitializeBuildStatus:

      正在创建“cmTC_b1812.dir\Debug\cmTC_b1812.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。

    AddCudaCompileDeps:

      E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe /E /nologo /showIncludes /TP /D__CUDACC__ /D__CUDACC_VER_MAJOR__=11 /D__CUDACC_VER_MINOR__=6 /D_WINDOWS /DCMAKE_INTDIR="Debug" /D_MBCS /DCMAKE_INTDIR="Debug" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" /I. /FIcuda_runtime.h /c E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\main.cu 

    项目“E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj”(1)正在节点 1 上生成“E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj”(1:2) (CudaBuildCore 个目标)。

    CudaBuildCore:

      Compiling CUDA source file main.cu...

      cmd.exe /C "C:\Users\Administrator\AppData\Local\Temp\tmp349ecf96509e429ebf34c69e1102aef8.cmd"

      "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe"  --use-local-env -ccbin "E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static --generate-code=arch=compute_89,code=[compute_89,sm_89] -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FdcmTC_b1812.dir\Debug\vc143.pdb /FS /Zi /RTC1 /MDd /GR" -o cmTC_b1812.dir\Debug\main.obj "E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\main.cu"

      

      E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe"  --use-local-env -ccbin "E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static --generate-code=arch=compute_89,code=[compute_89,sm_89] -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FdcmTC_b1812.dir\Debug\vc143.pdb /FS /Zi /RTC1 /MDd /GR" -o cmTC_b1812.dir\Debug\main.obj "E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\main.cu" 

      nvcc fatal   : Unsupported gpu architecture 'compute_89'

    E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 11.6.targets(790,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe"  --use-local-env -ccbin "E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static --generate-code=arch=compute_89,code=[compute_89,sm_89] -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FdcmTC_b1812.dir\Debug\vc143.pdb /FS /Zi /RTC1 /MDd /GR" -o cmTC_b1812.dir\Debug\main.obj "E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\main.cu"”已退出，返回代码为 1。 [E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj]

    已完成生成项目“E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj”(CudaBuildCore 个目标)的操作 - 失败。

    已完成生成项目“E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj”(默认目标)的操作 - 失败。

    

    生成失败。

    

    “E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj”(默认目标) (1) ->

    “E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj”(CudaBuildCore 目标) (1:2) ->

    (CudaBuildCore 目标) -> 

      E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 11.6.targets(790,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe"  --use-local-env -ccbin "E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64" -x cu    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"     --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static --generate-code=arch=compute_89,code=[compute_89,sm_89] -Xcompiler="/EHsc -Zi -Ob0" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W1 /nologo /Od /FdcmTC_b1812.dir\Debug\vc143.pdb /FS /Zi /RTC1 /MDd /GR" -o cmTC_b1812.dir\Debug\main.obj "E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\main.cu"”已退出，返回代码为 1。 [E:\Download\Compressed\SF_TRT_62-master_2\SF_TRT_62-master\build\CMakeFiles\CMakeScratch\TryCompile-gepjo4\cmTC_b1812.vcxproj]

    

        0 个警告

        1 个错误

    

    已用时间 00:00:00.49

    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:24 (enable_language)

Configuring incomplete, errors occurred!`
已经重新装一遍库了

**Comment by loadingfd** [comment]
是不是因为40系啊

**Comment by AMXZzzz** [comment]
> 是不是因为40系啊
换成cuda12 + cudann 8.9 + tensorRt8.6 GA ，需要VS2022，若存在其他版本的VS，请尝试卸载在安装VS2022

**Comment by JuZi233** [comment]
> > 是不是因为40系啊
> > 换成cuda12 + cudann 8.9 + tensorRt8.6 GA ，需要VS2022，若存在其他版本的VS，请尝试卸载在安装VS2022

原因是他编译器用的MinGW，Cuda无法用这玩意来compile，用vs自带的就可以通过，采坑实测

**Comment by AMXZzzz** [comment]
感谢JuZi233的指出。我认为该问题可以解决，如还要问题，请开始新话题。

**Comment by AMXZzzz** [comment]
感谢JuZi233的指出。我认为这个问题可以解决，如果还有问题，请开始新的话题。

**Comment by AMXZzzz** [comment]
感谢JuZi233的指出。我认为这个问题可以解决，如果还有问题，请开始新的话题。
