### ISSUE TITLE
没办法运行显示缺少exe

### ISSUE THREAD

**Issue by 2430468136** [AMXZzzz/SF_TRT_62#8]
我按照教程做完并且选择了mt运行但是显示缺少exe，但是我按照视频cmake没出现任何的错误
<img width="315" alt="42378a173d9589bb151106ee35ce46a" src="https://github.com/AMXZzzz/SF_TRT_62/assets/130272264/9253022b-0c7a-4be0-85b6-55c6e7d6130c">

**Comment by AMXZzzz** [comment]
需要 设置启动项

**Comment by AMXZzzz** [comment]
![4798944d9866631ab13bb7bc103a63ea](https://github.com/AMXZzzz/SF_TRT_62/assets/96624481/b590f45d-1372-49bf-96bb-c9b233c9e8f1)
